// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASSPy000wM8lfr20uEtDtpqX8rqhlsB1w',
    appId: '1:4412693216:web:d459d5c823917478e10e85',
    messagingSenderId: '4412693216',
    projectId: 'note-d8e55',
    authDomain: 'note-d8e55.firebaseapp.com',
    storageBucket: 'note-d8e55.appspot.com',
    measurementId: 'G-SGRN2Q3VHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB91Klc_aunfaG7yvZBdzEUXrzLPEd9b9Q',
    appId: '1:4412693216:android:67af306a29193d0de10e85',
    messagingSenderId: '4412693216',
    projectId: 'note-d8e55',
    storageBucket: 'note-d8e55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnyYmeE8rvk_NuNWMj_5QaxbEn8-j920k',
    appId: '1:4412693216:ios:8036d95158b85270e10e85',
    messagingSenderId: '4412693216',
    projectId: 'note-d8e55',
    storageBucket: 'note-d8e55.appspot.com',
    iosBundleId: 'com.example.tpFinalNotes',
  );
}
